### ISSUE TITLE
FileNotFoundError from subprocess.Popen(cmd)

### ISSUE THREAD

**Issue by TigerStone93** [thunil/TecoGAN#27]
Hello.
When I run python runGan.py 1 to test, I encountered the error below.

> Testing test case 1
Traceback (most recent call last):
  File "runGan.py", line 90, in <module>
    mycall(cmd1).communicate()
  File "runGan.py", line 21, in mycall
    return subprocess.Popen(cmd)
  File "C:\Users\user\Anaconda3\envs\tensorflow\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\user\Anaconda3\envs\tensorflow\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Please give me any solution or hint to solve this problem.

**Comment by LukeZhuohuiLi** [comment]
Use python 3.6.7, tensorflow has some problem with python 3.7.

**Comment by TigerStone93** [comment]
@LukeZhuohuiLi Thanks for your advice but it did not work under Python 3.6.7 too.

**Comment by LukeZhuohuiLi** [comment]
> @LukeZhuohuiLi Thanks for your advice but it did not work under Python 3.6.7 too.

I got the same problems, but I solved it either switch to python 3.6 or switch python 32bit to 64bit.

**Comment by TigerStone93** [comment]
@LukeZhuohuiLi Could I ask what environment that you used? Did you used Anaconda3(64bit)?

**Comment by LukeZhuohuiLi** [comment]
> @LukeZhuohuiLi Could I ask what environment did you used? Was it Anaconda3(64bit)?

I didn't use Anaconda because downgrading to python 3.6 in Anaconda takes a lot of time. Also  CUDA 10.1 is not compatible with pytorch. 
Check the right version and command from here: https://pytorch.org

Don't use python 3.7 since tensorflow is not compatible with python 3.7.

also, there is one problem that I can't remember, I ended up using python 3.6.7 64bit and add the Scripts folder to the environment variables(path). update the pip directly from CMD, rename the python.exe to python3.exe.
Then I use
pip3 install --ignore-installed --upgrade tensorflow-gpu 
pip3 install -r requirements.txt

python3 runGan.py 1 
You will see a lot of warnings, but the program will still run.

**Comment by TigerStone93** [comment]
@LukeZhuohuiLi
What a detailed desciption!
Thank you for your help.
I will try and let you know the result.

**Comment by TigerStone93** [comment]
@LukeZhuohuiLi It works perfectly on Python 3.5, Ubuntu 16.04.
Thank you so much.
Maybe there is a compatibility problem on Anaconda 3, Windows.

**Comment by EdisonBing** [comment]
including shell=True in subprocess function solved issue for me on win10 inside runGan.py, example line 21: subprocess.Popen(cmd)  -->   subprocess.Popen(cmd,shell=True)

**Comment by TigerStone93** [comment]
@EdisonBing Thank you for your commentary
